issuer: http://localhost:5556

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: litellm-gateway
    name: LiteLLM Gateway
    secret: dev-client-secret
    redirectURIs:
      - http://localhost:4000/sso/callback

enablePasswordDB: true

staticPasswords:
  # password: "test"  (bcrypt hash)
  - email: "test@example.com"
    hash: "$2a$10$DtZo7i8xHoPFezfOhTr/peHTo5l1oTi5fzvavNxfKca6k22MGrRvu"
    username: "test"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
